inventory_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),

]

main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml 
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 

from main.views import register
from main.views import login_user 
from main.views import logout_user

from main.views import edit_product
from main.views import delete_product

from main.views import get_product_json
from main.views import add_product_ajax

from main.views import remove_all_ajax
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('remove-all-ajax/', remove_all_ajax, name='remove_all_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/forms.py
from django.forms import ModelForm
from main.item import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name","amount", "price", "description"]

main/views.py
import datetime
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.urls import reverse

from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.item import Product
from django.http import HttpResponse
from django.core import serializers

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

from django.views.decorators.csrf import csrf_exempt


# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    if 'last_login' not in request.COOKIES:
        return redirect("main:login")
    context = {
        'name': request.user.username, # Nama kamu
        'class': 'PBP B', # Kelas PBP kamu
        'products': products,
        'last_login': request.COOKIES['last_login'],
        
    }

    return render(request, "main.html", context)

def create_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)  # Menggunakan request.FILES untuk menghandle gambar
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            return HttpResponseRedirect(reverse('main:show_main'))
    else :
        form = ProductForm()
    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Product.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))


@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, price=price, description=description, user=user)
        new_product.save()
        
        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def remove_all_ajax(request):
    if request.method == 'POST':
        id = request.POST.get("id")
        try:
            product = Product.objects.get(pk=id)
            product.delete()
            return HttpResponse(status=201)  # Status CREATED
        except Product.DoesNotExist:
            return HttpResponseNotFound("Product not found")

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    body {
        background-color: #618264;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh; /* Menggunakan 100% dari tinggi viewport */
        margin: 0;
        background-image: url('https://i.ibb.co/DGmQT10/kaos.jpg')
    }

    .login {
        background-color: #F1F0E8; /* Latar belakang berwarna biru muda */
        padding: 20px;
        border-radius: 10px;
        max-width: 300px;
        margin: 0 auto;
        text-align: center;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Efek bayangan */
    }

    .login h1 {
        color: #F2EE9D; /* Warna teks putih */
    }

    .login input[type="text"],
    .login input[type="password"] {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .login .btn {
        background-color: #FAE392; /* Tombol berwarna biru */
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .login .btn:hover {
        background-color: #F4D160; /* Warna tombol saat dihover */
    }
</style>

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>


{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% block content %}

<style>

  /* Tambahkan CSS untuk warna yang berbeda di baris terakhir */
  .last-row {
      background-color: #FCE09B; /* Warna background untuk baris terakhir */
      color: #000; /* Warna teks untuk baris terakhir */
  }

  body {
      background-color: #F8F0E5;
  }

  .card {
    background-color: #FFE9A0; /* Ganti kode warna dengan warna yang Anda inginkan */
    margin-bottom: 20px;
    width: 250px; /* Lebar kartu */
    height: 150px; /* Tinggi kartu */
  }

div.scroll-container {
  white-space: nowrap;
  padding: 10px;
  overflow-x: auto; /* Mengaktifkan scroll horizontal jika gambar melebihi lebar container */
}

div.scroll-container img {
  width: 200px; /* Ukuran gambar */
  height: auto; /* Biarkan tinggi gambar mengikuti proporsi aslinya */
  margin-right: 10px; /* Jarak antara gambar */
}

/* CSS untuk memposisikan Produk 1 dan 2 ke sebelah kanan */
.product-container {
    float: right; /* Mengatur container produk ke sisi kanan */
    margin-top: 10px; /* Jarak antara container produk dengan elemen di atasnya */
    margin-right: 10px; /* Jarak antara container produk dengan elemen di sebelah kirinya */
    width: 300px; /* Lebar container produk */
    text-align: right; /* Mengatur teks ke kanan di dalam container produk */
}

.product-item {
    text-align: left; /* Mengatur teks produk ke kiri di dalam container produk */
    margin-bottom: 10px; /* Jarak antara setiap item produk */
}


</style>


{% comment %} <p>Class: PBP B </p>  {% endcomment %}
<h2>Pilih Produk</h2>

  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid" style="background-color: #FFC288;">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">SHOPPING PAGE</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Welcome {{name}} !</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>


<div class="product-container">
  <div class="product-item">
<h5>Model 1</h5>
<ul>
    <li><cite>Name:</cite> Kaos Polos</li>
    <li><cite>Amount:</cite> 1</li>
    <li><cite>Description:</cite> Warna hitam</li>
    <li><cite>Price:</cite> Rp 70000</li>
    <li><cite>Ukuran:</cite> S - M</li>
    <button>Cek Out</button>
</ul>
</div>
<div class="product-item">
<h5>Model 2</h5>
<ul>
    <li><cite>Name:</cite> Kaos Bermotif</li>
    <li><cite>Amount:</cite> 1</li>
    <li><cite>Description:</cite> Request warna</li>
    <li><cite>Price:</cite> Rp 100000</li>
    <li><cite>Ukuran:</cite> L - XL</li>
    <button>Cek Out</button>
</ul>
<h5>Model 3</h5>
<ul>
    <li><cite>Name:</cite>Hoodie Mikey</li>
    <li><cite>Amount:</cite> 1</li>
    <li><cite>Description:</cite> Request warna</li>
    <li><cite>Price:</cite> Rp 200000</li>
    <li><cite>Ukuran:</cite> S - XL</li>
    <button>Cek Out</button>
</ul>
</div>
</div>

<div class="scroll-container">
  <img src="https://i.ibb.co/DWxXzkq/ff7319d50bc6eed1d76a95b7c25b9ec4.jpg" alt="Cinque Terre">
  <img src="https://i.ibb.co/TbfMq8y/dee8b64277601ca7ef5c7361364ca5ca.jpg" alt="Forest">
  <img src="https://i.ibb.co/9GYqhQz/f00bfcfb1feb44a12643ed759e7b8a79.jpg" alt="Northern Lights">
  <img src="https://i.ibb.co/G2c8Hjt/48ebdf5226e44f0d84907518310fc118.jpg" alt="Mountains">

  
<div class="row" id="product_cards"></div>

<div style ="background-color: #a7dbd8;">
  <table id ="product_table" style="background-color: #ADD8E6"> </table>
  </div>

<br />
<a href="{% url 'main:create_product' %}">
  <button>
      Add New Product
  </button>
</a>

<a href="{% url 'main:logout' %}">
<button>
    Logout
</button>
</a>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method = "POST" id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>


<script>
  async function getProducts() {
      return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
  }

  async function refreshProducts() {
    document.getElementById("product_table").innerHTML = ""
    const products = await getProducts();
    let htmlString = `<tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Date Added</th>
  </tr>`
  products.forEach((item) => {
      htmlString += `\n<tr>
      <td>${item.fields.name}</td>
      <td>${item.fields.price}</td>
      <td>${item.fields.description}</td>
      <td>${item.fields.date_added}</td>
  </tr>` 
  })
  
  document.getElementById("product_table").innerHTML = htmlString
}

  refreshProducts()

  function addProduct() {
    fetch("{% url 'main:add_product_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#form'))
    }).then(refreshProducts)

    document.getElementById("form").reset()
    return false
  }
document.getElementById("button_add").onclick = addProduct

</script>

<h5>Sesi terakhir login: {{ last_login }}</h5>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<style>
    body {
        background-color: #AAC8A7; /* Warna latar belakang biru */
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        background-image: url("https://i.ibb.co/gJFxNwT/4ddb4aa19261f494281306c07e05da56.jpg")
    }

    .login {
        background-color: #C3EDC0;
        padding: 20px;
        border-radius: 10px;
        text-align: center;
    }

    .login h1 {
        margin-bottom: 20px;
    }

    .login form table {
        margin: 0 auto;
    }

    .login input[type="text"],
    .login input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .login input[type="submit"] {
        background-color: #A2CDB0;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    .login input[type="submit"]:hover {
        background-color: #85A389;
    }

    .login ul {
        list-style: none;
        padding: 0;
    }

    .login ul li {
        color: red;
    }
</style>


<div class = "login">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}